export {default as Heading} from './Heading'
export {default as Text} from './Text'
export {default as Tag} from './Tag'
export {default as Button} from './Button'
export  {default as Input} from './Input'
export  {default as TextArea} from './TextArea'
export {default as Rating} from './Rating'
